{% set name = "asteval" %}
{% set version = "0.9.12" %}
{% set sha256 = "38f3b0592cae7e7f65adc687e37aad1824a8e518245603a29ec33258277e779b" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  noarch: python
  number: 1
  script: python -m pip install --no-deps --ignore-installed .

requirements:
  host:
    - pip
    - python
    - setuptools
    - six
    - numpy
  run:
    - python
    - setuptools
    - six
    - numpy

test:
  imports:
    - asteval

about:
  home: https://github.com/newville/asteval
  license: BSD
  license_file: LICENSE
  summary: 'Simple and robust expressions evaluator for Python'

  # The remaining entries in this section are optional, but recommended
  description: |
    asteval is a simple and robust evaluator of
    Python expressions and statements, using Python's ast module.
  doc_url: http://newville.github.io/asteval/
  dev_url: https://github.com/newville/asteval

extra:
  recipe-maintainers:
    - souravsingh
