travis:
  secure:
    BINSTAR_TOKEN: YpPWcoNhMbREkkLnlZUA9aAOPEPg5we/G/TQR6vbB3WWVaMh14tnNofbdgH3zuaH6lk7+TMW50JKXziW2xcWtcHn0OOW4DtQSiUUO9zF8ED9UsTHMCOrXbi4k7i40sxcEM2RFv75S39gMwrZva4Y6nrdMTsWOMM/gcXICCjpASlA/JCt4Id/DxKjOL7s9RXJvWv1pXU1xddjv4rj74w41mCfMTZ7fDd+PVGIxWrm6+Jel5Ow/sPHNAwb6BnyFP8xWoJBPAgs9zrH7DGwu64gWmIyCj/L/xGoogsLzDS87ArXw9DpT0mji3gI96kqb7GiiQe6mN4ADuHemFSMeziKZd1T8MrVKXV1wcIhzWi4c5mmwXNFrHuBzRsYm2TsPtvXC2jhRHjcCaoIPOUWicdZ7ftSMqQXYyzaxEkDMXK7E7evsSSMTNy/o+MqmaHb3eBZIPN0F3EEIxkhPIudI1y1x9AcHXszLtIN4ma/II2uhOAwfD+e44Qf2vA/4JzTHlPqaZ+upCeCoAU3r2FQkwK4dTVFWvWWxgPgDJmZpSHjl0F2Y23i9ZdQ6AvW0aBYBem5Hj1yYIxWu1q9+il40N9xd8OHhms0r5Z47nmoluxHrjPrf6HKX0Tflxug3TRbuJLD3x+7feEuxVqkPuC5L1ASyj3oZUI4UnziPPzuccQly80=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
