travis:
  secure:
    BINSTAR_TOKEN: Ad7djTjgnSbCXsoPrpg4v1EyaYzvbFyit/jBe+PUUSK0ChqOBudZMuiiJvtnBEXKgPOds3e2FwmiV23Tdlx9YhmXRJiEzy569qg8AllYbOkKzYpCZq0ED/68EanwwQDWylcIp4Fg9HGIVdbTiIiGhr+kRKtEiipqcJLy+yzdPyWHwBNrCOiRuu2uzt5koSlAM3oOlwBg/nWWhKR6PlyjpWJKsYLGBnKg0jz3tYwVBNJGPqAyyG7jkGcev5d1lCI0PEAkmjx4db8rntqH6ETOePQikDE4f14BP5QCnrJzMtbo+OEUZB8o6oiX6vuIhhK1zijR9zhxOHfGDS8UESLmwMjWEXGNmEruIuPg6mclt3CBB3W2rATqygqZCJsJM/z3mTq800pJvizY8S2nxVcukjyOUcQkV/n3NHSiREcDriTABlX103MUxux2c/oD5KzGP4mtKDWNhIAbso2NyWzyutKD6FVZAKGEevNqJentclrYteV/1ITqMy0vl6MAJqkYvpj+qwFpiMtOMAYv0AqPS2HNQwubE5lxdiDBN+l4V2KMtWZar/4KY9SbBYd5nSfM0B6gQYx0m/AMSm0UZjzZXWk+InFBejtpWBgOrOXedAGnU6UQZitYVdgWb27/LjOHmEuCC4HnBm1m9doraI6Jon5B/7+/jMvxdiaL88kxz6o=
appveyor:
  secure:
    BINSTAR_TOKEN: MP4hZYylDyUWEsrt3u3cod2sbFeRwUziH02mvQOdbjsTO/l1yIxDkP/76rSIjcGC
