travis:
  secure:
    BINSTAR_TOKEN: pyYJzTnS3gqfCryDgzstb+z0RFZIK3996al8CrTI8c7LqcCWwLpmxEOsS/hROY1O43brHYBGgajag/3ClTZBje3qHfV5cZ6Va4MRadg5dK08mcAFhpAjO1kcuaUeSVTg/Ju+3ftygcT6BXLRqTKnKAaEtsW3CzshSrbD03vkKFEE00S3CMYyWMH9SPPLDNd7rt0/CsNSrIomiXJxGfp/z/tdoixciKxUmniZRFDjPgcZ4xvtbs7qBZW/IIAFNOFmw3rnNX6M8xZei7al8Iu7xWgNbK87+LMmQojYVz874JyAmpwtRUfQek+gRVef6+nxcXVgCmiPjI/Mh+qu82+gHzEHxlM/NYBv/TQSYF1WnuU44P0LK2qRcQMMRSVOXH1KuOhj+ZVj4SaWDggoON/Jx9Z4zet6cNTYqYLJvfefN+CGT5pc79U4Max7rUjFDSDRR3w4IrNcST3gC26cCAucNhySEAKi5WZknTrdVQh2zS/i9mVyzbKrcWIfFbMRxXfYDUA3T6I9u5UP+yEtZWnQ4FnqVj1kx2eGDfgUzbsk9ujWVmdij+3EW5eam8QQy9o7JaZJ/jCMzlKE3vjx8x3RjahlQtG4JnP1kBhqaUVCN9pkBp6kRxQJd+87+tVonRkhEo6v2TX3YRdjI/0TE+mdhXJYf7VvWRzdm2VKEB55fIg=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
conda_forge_output_validation: false
